namespace GuiToolkit
{
	/// \brief static class for determining loca plural forms.
	/// 
	/// This class consists of an internal part (this one) and a user part, which is generated by LocaPluralProcessor according to the language rules in the PO files.
	/// The generated class implements GetPluralIdx.
	/// The "partial" feature of C# feels a bit weird and awkward, but it is very handy - it's the "poor man's inheritance" for static classes.
	public static partial class LocaPlurals
	{
		public static (int numPluralForms, int pluralIdx) GetPluralIdx(string _languageId, int _number)
		{
			int numPluralForms = 0;
			int pluralIdx = 0;

			GetPluralIdx(_languageId, _number, ref numPluralForms, ref pluralIdx);

			return (numPluralForms, pluralIdx);
		}

		static partial void GetPluralIdx(string _languageId, int _number, ref int _numPluralForms, ref int _pluralIdx);
	}
}
