var dir_870dba6ac0d3672b928395fe1e1be64f =
[
    [ "OneTime", "dir_ba637419c8e507399b9475f919e9148f.html", "dir_ba637419c8e507399b9475f919e9148f" ],
    [ "SafeDeleteWindow", "dir_b6928257071edcf4095df897534cfb36.html", "dir_b6928257071edcf4095df897534cfb36" ],
    [ "CloneFolder.cs", "_clone_folder_8cs.html", null ],
    [ "ConfigManagerWindow.cs", "_config_manager_window_8cs.html", "_config_manager_window_8cs" ],
    [ "ConvertUiMainStyleConfig.cs", "_convert_ui_main_style_config_8cs.html", null ],
    [ "CreatePackageVariantInProject.cs", "_create_package_variant_in_project_8cs.html", null ],
    [ "DebugTools.cs", "_debug_tools_8cs.html", null ],
    [ "GameScreenshotTool.cs", "_game_screenshot_tool_8cs.html", null ],
    [ "GameSpeed.cs", "_game_speed_8cs.html", "_game_speed_8cs" ],
    [ "GradientSpriteGeneratorWindow.cs", "_gradient_sprite_generator_window_8cs.html", "_gradient_sprite_generator_window_8cs" ],
    [ "KerningTableTool.cs", "_kerning_table_tool_8cs.html", "_kerning_table_tool_8cs" ],
    [ "LoadViewInEveryScene.cs", "_load_view_in_every_scene_8cs.html", null ],
    [ "OnlyMainSceneOnPlay.cs", "_only_main_scene_on_play_8cs.html", "_only_main_scene_on_play_8cs" ],
    [ "PoFixer.cs", "_po_fixer_8cs.html", null ],
    [ "PoFixerAssetPostprocessor.cs", "_po_fixer_asset_postprocessor_8cs.html", "_po_fixer_asset_postprocessor_8cs" ],
    [ "RenameFolder.cs", "_rename_folder_8cs.html", null ],
    [ "ReplaceComponentsWindow.cs", "_replace_components_window_8cs.html", "_replace_components_window_8cs" ],
    [ "SaveProjectOnLoseFocus.cs", "_save_project_on_lose_focus_8cs.html", null ],
    [ "SceneChangeTracker.cs", "_scene_change_tracker_8cs.html", null ],
    [ "SceneMenuGenerator.cs", "_scene_menu_generator_8cs.html", null ],
    [ "SceneMenuGeneratorTemplate.cs", "_scene_menu_generator_template_8cs.html", null ],
    [ "ScreenshotOverlayTool.cs", "_screenshot_overlay_tool_8cs.html", "_screenshot_overlay_tool_8cs" ],
    [ "SetAllUiLocaGroups.cs", "_set_all_ui_loca_groups_8cs.html", null ],
    [ "UiResolutionRescalerWindow.cs", "_ui_resolution_rescaler_window_8cs.html", "_ui_resolution_rescaler_window_8cs" ]
];